require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/readable_texts", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # ReadableText. As you add validations to ReadableText, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ReadableText.create! valid_attributes
      get readable_texts_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      readable_text = ReadableText.create! valid_attributes
      get readable_text_url(readable_text)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_readable_text_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      readable_text = ReadableText.create! valid_attributes
      get edit_readable_text_url(readable_text)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ReadableText" do
        expect {
          post readable_texts_url, params: { readable_text: valid_attributes }
        }.to change(ReadableText, :count).by(1)
      end

      it "redirects to the created readable_text" do
        post readable_texts_url, params: { readable_text: valid_attributes }
        expect(response).to redirect_to(readable_text_url(ReadableText.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ReadableText" do
        expect {
          post readable_texts_url, params: { readable_text: invalid_attributes }
        }.to change(ReadableText, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post readable_texts_url, params: { readable_text: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested readable_text" do
        readable_text = ReadableText.create! valid_attributes
        patch readable_text_url(readable_text), params: { readable_text: new_attributes }
        readable_text.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the readable_text" do
        readable_text = ReadableText.create! valid_attributes
        patch readable_text_url(readable_text), params: { readable_text: new_attributes }
        readable_text.reload
        expect(response).to redirect_to(readable_text_url(readable_text))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        readable_text = ReadableText.create! valid_attributes
        patch readable_text_url(readable_text), params: { readable_text: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested readable_text" do
      readable_text = ReadableText.create! valid_attributes
      expect {
        delete readable_text_url(readable_text)
      }.to change(ReadableText, :count).by(-1)
    end

    it "redirects to the readable_texts list" do
      readable_text = ReadableText.create! valid_attributes
      delete readable_text_url(readable_text)
      expect(response).to redirect_to(readable_texts_url)
    end
  end
end
